### ISSUE TITLE
Fail to create an instance of the launcher : "error":"invalid sensitive value definition"

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/launcher-operator#15]
### Issue

When the following CR is deployed 

```
apiVersion: launcher.fabric8.io/v1alpha1
kind: Launcher
metadata:
  name: launcher
spec:

####### OpenShift Configuration (optional)
openshift:
  consoleUrl: "https://192.168.65.49:8443"

####### Git Configuration
git:
  provider: github
  token:
    valueFrom:
      secretKeyRef:
        name: launcher-secrets
        key: github-token
```

on okd-3.11, then the following error is reported within the log of the operator

```
{"level":"info","ts":1554881805.0458868,"logger":"controller_launcher","msg":"Reconciling Launcher\n","Namespace":"myproject","Name":"launcher"}
--
  | {"level":"info","ts":1554881805.0496285,"logger":"controller_launcher","msg":"Launcher template has been loaded"}
  | {"level":"info","ts":1554881805.0852718,"logger":"controller_launcher","msg":"Launcher template has been processed","Namespace":"myproject"}
  | {"level":"error","ts":1554881805.0855715,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"launcher-controller","request":"myproject/launcher","error":"invalid sensitive value definition",
"stacktrace":"fabric8-launcher/launcher-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nfabric8-launcher/launcher-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.
(*Controller).processNextWorkItem\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\nfabric8-launcher/launcher-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.
(*Controller).Start.func1\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nfabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nfabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nfabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/Users/ia3andy/go/src/fabric8-launcher/launcher-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

### Steps

```
go get github.com/fabric8-launcher/launcher-operator
cd ~/Code/go-workspace/src/github.com/fabric8-launcher/launcher-operator
minishift start
oc login -u system:admin
oc adm policy add-cluster-role-to-user cluster-admin admin
oc login -u admin -p admin
oc create -R -f ./deploy
 oc create secret generic launcher-secrets --from-literal=github-token=launcher
secret/launcher-secrets created
oc create -f example/launcher_cr.yaml
```

**Comment by cmoulliard** [comment]
I changed the syntax of the CR and that works now

```
apiVersion: launcher.fabric8.io/v1alpha1
kind: Launcher
metadata:
  name: launcher
spec:
  ####### OpenShift Configuration (optional)
  openshift:
    consoleUrl: "https://192.168.65.49:8443"
  ####### Git Configuration
  git:
    provider: github
    token:
      valueFrom:
        secretKeyRef:
          name: launcher-secrets
          key: github-token
```
